import { AttributeType } from './normalize';
import { Swatch } from './catalogue';

export interface AttributeMeta { key: string; type: AttributeType; unit?: string | null }

export const ATTRIBUTE_META: Record<string, AttributeMeta> = {
  'Colour': { key: 'colour', type: 'colour' },
  'Brand': { key: 'brand', type: 'select' },
  'Make': { key: 'make', type: 'select' },
  'Model': { key: 'model', type: 'text' },
  'Year': { key: 'year', type: 'year' },
  'Mileage (km)': { key: 'mileage', type: 'measurement', unit: 'km' },
  'Engine size': { key: 'engine-size', type: 'measurement', unit: 'cc' },
  'Engine (cc)': { key: 'engine-size', type: 'measurement', unit: 'cc' },
  'Transmission': { key: 'transmission', type: 'select' },
  'Fuel': { key: 'fuel', type: 'select' },
  'Drive': { key: 'drive', type: 'select' },
  'Body type': { key: 'body-type', type: 'select' },
  'Seats': { key: 'seats', type: 'number' },
  'Condition': { key: 'condition', type: 'select' },
  'Registration': { key: 'registration', type: 'text' },
  'Location': { key: 'location', type: 'text' },
  'Storage': { key: 'storage', type: 'select' },
  'RAM': { key: 'ram', type: 'select' },
  'Screen size': { key: 'screen-size', type: 'measurement', unit: '"' },
  'Battery': { key: 'battery', type: 'measurement', unit: 'mAh' },
  'Camera': { key: 'camera', type: 'text' },
  'Network': { key: 'network', type: 'select' },
  'SIM': { key: 'sim', type: 'select' },
  'Warranty': { key: 'warranty', type: 'text' },
  'Processor': { key: 'processor', type: 'text' },
  'Graphics': { key: 'graphics', type: 'text' },
  'Operating system': { key: 'operating-system', type: 'select' },
  'Resolution': { key: 'resolution', type: 'select' },
  'Power': { key: 'power', type: 'measurement', unit: 'W' },
  'Capacity': { key: 'capacity', type: 'text' },
  'Voltage': { key: 'voltage', type: 'measurement', unit: 'V' },
  'Wattage': { key: 'wattage', type: 'measurement', unit: 'W' },
  'Weight': { key: 'weight', type: 'measurement', unit: 'kg' },
  'Volume': { key: 'volume', type: 'measurement', unit: 'ml' },
  'Length': { key: 'length', type: 'measurement', unit: null },
  'Width': { key: 'width', type: 'measurement', unit: null },
  'Height': { key: 'height', type: 'measurement', unit: null },
  'Dimensions': { key: 'dimensions', type: 'text' },
  'Material': { key: 'material', type: 'select' },
  'Fit': { key: 'fit', type: 'select' },
  'Care': { key: 'care', type: 'text' },
  'Made in': { key: 'made-in', type: 'select' },
  'Sizes available': { key: 'sizes-available', type: 'text' },
  'Size': { key: 'size', type: 'select' },
  'Waist': { key: 'waist', type: 'select' },
  'Chest': { key: 'chest', type: 'select' },
  'Age': { key: 'age', type: 'select' },
  'Shade': { key: 'shade', type: 'select' },
  'Finish': { key: 'finish', type: 'select' },
  'Package': { key: 'package', type: 'select' },
  'Pack size': { key: 'pack-size', type: 'select' },
  'Pack': { key: 'pack', type: 'select' },
  'Portion': { key: 'portion', type: 'select' },
  'Pages': { key: 'pages', type: 'number' },
  'Author': { key: 'author', type: 'text' },
  'Publisher': { key: 'publisher', type: 'text' },
  'ISBN': { key: 'isbn', type: 'text' },
  'Language': { key: 'language', type: 'select' },
  'Breed': { key: 'breed', type: 'select' },
  'Vaccinated': { key: 'vaccinated', type: 'boolean' },
  'Sex': { key: 'sex', type: 'select' },
  'Expiry': { key: 'expiry', type: 'date' },
  'Bedrooms': { key: 'bedrooms', type: 'number' },
  'Bathrooms': { key: 'bathrooms', type: 'number' },
  'Furnished': { key: 'furnished', type: 'boolean' },
  'Parking': { key: 'parking', type: 'boolean' },
  'Land title': { key: 'land-title', type: 'select' },
  'Rent period': { key: 'rent-period', type: 'select' },
  'Serves': { key: 'serves', type: 'number' },
  'Duration': { key: 'duration', type: 'text' },
  'Area covered': { key: 'area-covered', type: 'text' },
  'Availability': { key: 'availability', type: 'text' },
  'Experience': { key: 'experience', type: 'text' },
  'What is included': { key: 'what-is-included', type: 'text' },
  'Order notice (days)': { key: 'order-notice', type: 'number' },
  'Order notice': { key: 'order-notice', type: 'text' },
  'Allergens': { key: 'allergens', type: 'text' },
  'Ingredients': { key: 'ingredients', type: 'text' },
  'Flavour': { key: 'flavour', type: 'select' },
  'Origin': { key: 'origin', type: 'select' },
  'Halal': { key: 'halal', type: 'boolean' },
  'Organic': { key: 'organic', type: 'boolean' },
  'Smart TV': { key: 'smart-tv', type: 'boolean' },
  'Wireless': { key: 'wireless', type: 'boolean' },
  'Bluetooth': { key: 'bluetooth', type: 'boolean' },
  'Waterproof': { key: 'waterproof', type: 'boolean' },
  'Fast charging': { key: 'fast-charging', type: 'boolean' },
  'Noise cancelling': { key: 'noise-cancelling', type: 'boolean' },
  'Assembly': { key: 'assembly', type: 'select' },
  'Delivery': { key: 'delivery', type: 'text' },
  'Installation': { key: 'installation', type: 'text' },
  'Energy rating': { key: 'energy-rating', type: 'select' },
  'Type': { key: 'type', type: 'select' },
  'Gears': { key: 'gears', type: 'number' },
  'Wheel size': { key: 'wheel-size', type: 'select' },
  'Frame size': { key: 'frame-size', type: 'select' },
  'Load index': { key: 'load-index', type: 'text' },
  'Part number': { key: 'part-number', type: 'text' },
  'Fits make and model': { key: 'fits', type: 'text' },
  'Fits model': { key: 'fits', type: 'text' },
  'Grade': { key: 'grade', type: 'select' },
  'Sold per': { key: 'sold-per', type: 'select' },
  'Pieces': { key: 'pieces', type: 'number' },
  'Pieces in set': { key: 'pieces', type: 'number' },
  'Stone': { key: 'stone', type: 'select' },
  'Strap': { key: 'strap', type: 'select' },
  'Water resistant': { key: 'water-resistant', type: 'boolean' },
  'Sole': { key: 'sole', type: 'select' },
  'Closure': { key: 'closure', type: 'select' },
  'Compartments': { key: 'compartments', type: 'number' },
  'Wheels': { key: 'wheels', type: 'boolean' },
  'Skin type': { key: 'skin-type', type: 'select' },
  'Key ingredients': { key: 'key-ingredients', type: 'text' },
  'Texture': { key: 'texture', type: 'select' },
  'Density': { key: 'density', type: 'select' },
  'Lace type': { key: 'lace-type', type: 'select' },
  'Can be dyed': { key: 'can-be-dyed', type: 'boolean' },
  'Dosage': { key: 'dosage', type: 'text' },
  'Max user weight': { key: 'max-user-weight', type: 'measurement', unit: 'kg' },
  'Thickness': { key: 'thickness', type: 'measurement', unit: 'mm' },
  'Bulb type': { key: 'bulb-type', type: 'select' },
  'Fitting': { key: 'fitting', type: 'select' },
  'Colour temperature': { key: 'colour-temperature', type: 'select' },
  'Power source': { key: 'power-source', type: 'select' },
  'Platform': { key: 'platform', type: 'select' },
  'Games included': { key: 'games-included', type: 'text' },
  'Megapixels': { key: 'megapixels', type: 'measurement', unit: 'MP' },
  'Video': { key: 'video', type: 'select' },
  'Lens mount': { key: 'lens-mount', type: 'select' },
  'Flight time': { key: 'flight-time', type: 'text' },
  'Range': { key: 'range', type: 'text' },
  'Night vision': { key: 'night-vision', type: 'boolean' },
  'Battery type': { key: 'battery-type', type: 'select' },
  'Battery life': { key: 'battery-life', type: 'text' },
  'Ports': { key: 'ports', type: 'text' },
  'Refresh rate': { key: 'refresh-rate', type: 'measurement', unit: 'Hz' },
  'Cartridge': { key: 'cartridge', type: 'text' },
  'Colour printing': { key: 'colour-printing', type: 'boolean' },
  'Channels': { key: 'channels', type: 'select' },
  'Subwoofer': { key: 'subwoofer', type: 'boolean' },
  'Connector': { key: 'connector', type: 'select' },
  'Cable length': { key: 'cable-length', type: 'measurement', unit: 'm' },
  'Accuracy': { key: 'accuracy', type: 'text' },
  'Certified': { key: 'certified', type: 'boolean' },
  'Application': { key: 'application', type: 'text' },
  'Harvested': { key: 'harvested', type: 'text' },
  'Storage drives': { key: 'storage', type: 'select' },
  'Team or season': { key: 'team-or-season', type: 'text' },
  'Official': { key: 'official', type: 'boolean' },
  'Accessories included': { key: 'accessories-included', type: 'text' },
  'Artist': { key: 'artist', type: 'text' },
  'Framed': { key: 'framed', type: 'boolean' },
  'Made by': { key: 'made-by', type: 'text' },
  'Custom orders': { key: 'custom-orders', type: 'boolean' },
  'Setup included': { key: 'setup-included', type: 'boolean' },
  'Includes service': { key: 'includes-service', type: 'boolean' },
  'Menu': { key: 'menu', type: 'text' },
  'Hot or cold': { key: 'hot-or-cold', type: 'select' },
  'Delivery area': { key: 'delivery-area', type: 'text' },
  'Delivery days': { key: 'delivery-days', type: 'text' },
  'Water & power': { key: 'water-and-power', type: 'text' },
  'Access road': { key: 'access-road', type: 'select' },
  'Distance from tarmac': { key: 'distance-from-tarmac', type: 'measurement', unit: 'km' },
  'With driver': { key: 'with-driver', type: 'boolean' },
  'Fuel included': { key: 'fuel-included', type: 'boolean' },
  'Scent notes': { key: 'scent-notes', type: 'text' },
  'Longevity': { key: 'longevity', type: 'text' },
  'Original or inspired': { key: 'original-or-inspired', type: 'select' },
  'Coverage': { key: 'coverage', type: 'select' },
  'Heat settings': { key: 'heat-settings', type: 'number' },
  'Hair type': { key: 'hair-type', type: 'select' },
  'Age range': { key: 'age-range', type: 'text' },
  'Batteries': { key: 'batteries', type: 'text' },
  'Dishwasher safe': { key: 'dishwasher-safe', type: 'boolean' },
  'Alcohol %': { key: 'alcohol', type: 'measurement', unit: '%' },
  'Chilled': { key: 'chilled', type: 'boolean' },
  'Pattern': { key: 'pattern', type: 'select' },
  'Sizes': { key: 'size', type: 'select' },
};

export const REQUIRED_DETAILS: Record<string, string[]> = {
  cars: ['Make', 'Model', 'Year', 'Mileage (km)', 'Transmission', 'Fuel'],
  motorcycles: ['Make', 'Model', 'Year', 'Engine (cc)'],
  phones: ['Brand', 'Model'],
  computers: ['Brand', 'Model', 'Processor', 'RAM', 'Storage'],
  property: ['Bedrooms', 'Location'],
  livestock: ['Breed', 'Age'],
  books: ['Author'],
};

export const LOW_RISK_ATTRIBUTES = new Set([
  'size', 'waist', 'chest', 'colour', 'storage', 'ram', 'material', 'capacity', 'length', 'width', 'height', 'weight', 'volume',
  'pack-size', 'pack', 'portion', 'shade', 'finish', 'package', 'age', 'wattage', 'power', 'screen-size', 'fit', 'flavour',
  'frame-size', 'wheel-size', 'type', 'engine-size', 'transmission', 'fuel', 'drive', 'body-type', 'network', 'sim', 'resolution',
  'operating-system', 'platform', 'channels', 'connector', 'bulb-type', 'fitting', 'grade', 'sold-per', 'stone', 'strap', 'sole',
  'closure', 'skin-type', 'texture', 'density', 'lace-type', 'hair-type', 'breed', 'sex', 'language', 'origin', 'made-in', 'pattern',
  'rent-period', 'land-title', 'energy-rating', 'coverage', 'assembly', 'battery-type', 'video', 'lens-mount', 'hot-or-cold', 'access-road',
]);

export const GENERIC_PALETTE: Swatch[] = [
  { name: 'Black', hex: '#111111' }, { name: 'White', hex: '#F5F5F5' }, { name: 'Navy blue', hex: '#1F3A93' },
  { name: 'Blue', hex: '#2563EB' }, { name: 'Sky blue', hex: '#7DD3FC' }, { name: 'Green', hex: '#16A34A' },
  { name: 'Red', hex: '#DC2626' }, { name: 'Orange', hex: '#F97316' }, { name: 'Yellow', hex: '#FACC15' },
  { name: 'Pink', hex: '#EC4899' }, { name: 'Purple', hex: '#7C3AED' }, { name: 'Grey', hex: '#9CA3AF' },
  { name: 'Brown', hex: '#8B5E3C' }, { name: 'Gold', hex: '#D4AF37' }, { name: 'Silver', hex: '#C0C0C0' },
];

export const KIND_SYNONYMS: { category: string; kind: string; terms: string[] }[] = [
  { category: 'fashion', kind: 'Trousers', terms: ['trouser', 'pants', 'pant', 'slacks'] },
  { category: 'mens', kind: 'Trousers', terms: ['trouser', 'pants', 'pant', 'slacks'] },
  { category: 'womens', kind: 'Trousers', terms: ['trouser', 'pants', 'pant'] },
  { category: 'fashion', kind: 'T-shirts', terms: ['tshirt', 't shirt', 'tee', 'tees', 't-shirt'] },
  { category: 'mens', kind: 'T-shirts', terms: ['tshirt', 't shirt', 'tee', 'tees', 't-shirt'] },
  { category: 'shoes', kind: 'Sneakers', terms: ['trainers', 'sneaker', 'kicks', 'running shoes'] },
  { category: 'shoes', kind: 'Sandals', terms: ['sandal', 'flip flops'] },
  { category: 'shoes', kind: 'Heels', terms: ['high heels', 'heel', 'stilettos'] },
  { category: 'phones', kind: 'Smartphones', terms: ['phone', 'smartphone', 'mobile phone', 'mobile', 'handset', 'cellphone'] },
  { category: 'phones', kind: 'Tablets', terms: ['tablet', 'ipad'] },
  { category: 'phones', kind: 'Earphones', terms: ['earbuds', 'earpods', 'airpods', 'headphones', 'earphone'] },
  { category: 'phones', kind: 'Chargers & cables', terms: ['charger', 'cable', 'usb cable', 'adapter'] },
  { category: 'phones', kind: 'Power banks', terms: ['powerbank', 'power bank'] },
  { category: 'computers', kind: 'Laptops', terms: ['laptop', 'notebook', 'macbook'] },
  { category: 'computers', kind: 'Desktops', terms: ['desktop', 'pc', 'computer'] },
  { category: 'tv-audio', kind: 'Smart TVs', terms: ['tv', 'television', 'smart tv', 'flat screen'] },
  { category: 'tv-audio', kind: 'Bluetooth speakers', terms: ['speaker', 'bluetooth speaker', 'woofer'] },
  { category: 'appliances', kind: 'Fridges & freezers', terms: ['fridge', 'refrigerator', 'freezer'] },
  { category: 'appliances', kind: 'Washing machines', terms: ['washing machine', 'washer'] },
  { category: 'appliances', kind: 'Cookers & ovens', terms: ['cooker', 'oven', 'gas cooker', 'stove'] },
  { category: 'motorcycles', kind: 'Boda boda', terms: ['boda', 'boda boda', 'motorbike', 'motorcycle', 'bike'] },
  { category: 'cars', kind: 'SUV', terms: ['suv', '4x4', 'jeep'] },
  { category: 'cars', kind: 'Saloon', terms: ['saloon', 'sedan'] },
  { category: 'cars', kind: 'Pickup', terms: ['pickup', 'pick up', 'pick-up'] },
  { category: 'furniture', kind: 'Sofas', terms: ['sofa', 'couch', 'sofa set'] },
  { category: 'furniture', kind: 'Beds', terms: ['bed', 'bed frame'] },
  { category: 'home', kind: 'Mattresses', terms: ['mattress'] },
  { category: 'hair', kind: 'Wigs', terms: ['wig', 'lace wig', 'frontal'] },
  { category: 'hair', kind: 'Braids & extensions', terms: ['braids', 'extensions', 'weave'] },
  { category: 'groceries', kind: 'Rice & grains', terms: ['rice'] },
  { category: 'groceries', kind: 'Cooking oil', terms: ['oil', 'cooking oil'] },
  { category: 'drinks', kind: 'Water', terms: ['mineral water', 'bottled water', 'drinking water'] },
  { category: 'bakery', kind: 'Cakes', terms: ['cake', 'birthday cake'] },
  { category: 'property', kind: 'Houses for rent', terms: ['house for rent', 'rental', 'apartment', 'flat'] },
  { category: 'property', kind: 'Land', terms: ['plot', 'plots', 'land for sale'] },
];

export const BRAND_SYNONYMS: { brand: string; terms: string[] }[] = [
  { brand: 'Apple', terms: ['iphone', 'ipad', 'macbook', 'airpods', 'imac', 'apple watch'] },
  { brand: 'Samsung', terms: ['galaxy'] },
  { brand: 'Google', terms: ['pixel'] },
  { brand: 'Xiaomi', terms: ['redmi', 'poco', 'mi'] },
  { brand: 'Mercedes-Benz', terms: ['mercedes', 'benz'] },
  { brand: 'Volkswagen', terms: ['vw'] },
  { brand: 'Land Rover', terms: ['range rover', 'defender', 'discovery'] },
  { brand: 'Toyota', terms: ['harrier', 'premio', 'noah', 'vitz', 'hiace', 'land cruiser', 'prado', 'corolla', 'rav4'] },
  { brand: 'Nissan', terms: ['x-trail', 'xtrail', 'note', 'juke', 'patrol'] },
  { brand: 'Subaru', terms: ['forester', 'outback', 'impreza'] },
  { brand: 'HP', terms: ['hewlett packard', 'hewlett-packard'] },
  { brand: 'Sony', terms: ['playstation', 'ps5', 'ps4', 'bravia'] },
  { brand: 'Microsoft', terms: ['xbox', 'surface'] },
  { brand: 'Nintendo', terms: ['switch'] },
];
